services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./web
    ports:
      - "8080:8080"
    environment:
      - REMOTE_HOST=http://backend:80/api/v1
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata: